baseurl = "https://genexp.me/"
theme = "cocoa-eh"
builddrafts = true
canonifyurls = true
contentdir = "content"
languageCode = "en-US"
layoutdir = "layouts"
publishdir = "public"
author = "Brian Corrigan"
title = "General Exception"
disqusshortname = ""
pluralizelisttitles = false

[permalinks]
blog = "blog/:slug/"

[params]
dateform = "Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
description = "General Exception"
copyright = "Copyright © 2018 Brian Corrigan"
copyrightUrl = "https://creativecommons.org/licenses/by-nc-nd/4.0/"
logofile = "img/if_space-invader_2981852.png"
faviconfile = "img/if_space-invader_2981852.png"
highlightjs = true
progressively = true
share = true
# Share to googleplus, twitter, fb, linkedin by default
# disable by setting share_on_<social network> = false
share_on_googleplus = false
latestpostcount = 5
github = "genexp"
# email = "you@example.com"
linkedin = "briancorrigan"
twitter = "genexp"
facebook = "genexp"
social_banner = "img/if_space-invader_2981852.png"
usesmallsummarycard = true
posts_navigation = true
# issoHost = "comments.domain.tld:1234"
githubRepo = "genexp/genexp.me/tree/master"
small_banner_logo = false

[params.colors]
identifier = "#527fc1"
identifier_dark = "#1a3152"
trivial = "#6a7a8b"
foreground = "#181d2a"
background = "#f9f9f9"
background_dark = "#282a36"
code = "#87a5d2"
type = "#97d28b"
special = "#ffcb8d"
value = "#96c2d7"
statement = "#ff8e91"